### ISSUE TITLE
Could not load file or assembly System.Net.Mqtt.resources.dll

### ISSUE THREAD

**Issue by ciani** [xamarin/mqtt#114]
Hi there,

I am trying to connect to my Mqtt server from my Xamarin Forms App. I made an implementation on iOS this way:

```
public async Task CreateClientAsync(string serverIp, string serverPort)
{
    client = await MqttClient.CreateAsync(serverIp, serverIp);
}

public async Task<bool> Connect(string clientId, string user, string password)
{            
    credentials = new MqttClientCredentials(clientId, user, password);
    await client.ConnectAsync(credentials);
    return client.IsConnected;
}
```

But i always get this exception when I call to the method ConnectAsync(credentials)

Exception:

_System.IO.FileNotFoundException: Could not load file or assembly '/Users/ciani/Library/Developer/CoreSimulator/Devices/18F2ACE9-10B6-48F5-957D-38A72BE47BCF/data/Containers/Bundle/Application/434A0A8B-7CD0-4790-84EA-74516FCFFFBD/SmartTracker.iOS.app/en-US/System.Net.Mqtt.resources.dll' or one of its dependencies occurred_

What I am doing wrong?

**Comment by kzu** [comment]
@mauroa have you seen this?

**Comment by mauroa** [comment]
This should be already fixed. Try using latest Xamarin Forms together with latest MQTT.
Also, soon we will be uploading a new MQTT version with bug fixing and improvements.
