### ISSUE TITLE
Heartbeat monitoring 

### ISSUE THREAD

**Issue by Magnabatt** [xamarin/mqtt#119]
Hi,

Is it possible to monitor the client to broker connection? So that when it drops out I can sent an alert and/or reconnect?

Thanks.

**Comment by mauroa** [comment]
The IMqttClient interface has a Disconnected event, which you can use to hook and monitor disconnections. The args of the event will provide you with the reason of the disconnection

**Comment by mauroa** [comment]
Closing this issue given that It has been answered. Feel free to re open if you have any related problem.
