### ISSUE TITLE
No session has been found for client 

### ISSUE THREAD

**Issue by eppak** [xamarin/mqtt#121]
Hello,
i tried to connect to a mosquitto broker, on ConnectAsync i get  "No session has been found for client" disconnect error, no matter if cleansession is true or false.

Any ideas if is a bug or some strict feature of mqtt? (i'm connected to this server with same credentials with other libraries).
Thanks

**Comment by mauroa** [comment]
Hello,
Thanks for reporting. Can you check if the ClientId that you pass to the MqttClientCredentials on the ConnectAsync method is the same that appears in the error message "No session has been found for client {0}"?

It's a very strange error and it's the first time it's reported. Other users has been using other Brokers too and there were no issues like this. Also, if you can share the client logs, it could be very useful.

We use System.Diagnostics infrastructure in our libraries, so it's a matter if adding a TraceSource and a Tracing level to be able to get the logs.

This is a sample you can use to enable the Mqtt logs (you need to import System.Diagnostics):

var source = new TraceSource("System.Net.Mqtt", defaultLevel: SourceLevels.All);

source.Listeners.Add(new TextWriterTraceListener("test.log"));
source.Switch.Level = SourceLevels.All;

Thanks

**Comment by eppak** [comment]
Hello,
here complete output log of the app (i removed my refers). Another thing that may help you it that. while connecting, there is a kind of loop (auto-reconnection?) that the lib do on connection after some attempts it crash. Another thing is that now i use tha paho inplementation with no connection problems.
Thanks in advance.

[System.Net.Mqtt.txt](https://github.com/xamarin/mqtt/files/1151724/System.Net.Mqtt.txt)

**Comment by mauroa** [comment]
This has already been fixed in the recent commits and it will be available in the next release coming soon. Closing this issue.
