### ISSUE TITLE
publishing from mosquitto_pub command

### ISSUE THREAD

**Issue by nm-a** [xamarin/mqtt#124]
Hi,
I am trying to publish data using "mosquitto_pub" command.

`C:\Users\Administrator>mosquitto_pub -d -t path -m "Hello from Terminal window 2!" -h <<ipaddress>>
Client mosqpub/16196-WIN-LNKCV sending CONNECT
Error: The connection was lost.`

This the error message that I am getting; from C# code both server & client are working fine. Finally I want publish from Raspberry Pi using "c / c++" library. Can you help me to connect this from the device.

**Currently I am using this library to connect from the device:**
https://github.com/eclipse/mosquitto

**C# Server Code:**
`
    class Program
    {
        private static IMqttServer server;
        private static IMqttClient client;
        private static MqttConfiguration Configuration { get; set; }

        static void Main(string[] args)
        {
            usedPorts = new ConcurrentBag<int>();

            server = GetServerAsync();
            client = GetClientAsync();
            server.Start();

            var subscriber1 = GetClientAsync();

            var clientId1 = GetClientId();
            var clientId2 = GetClientId();

            subscriber1.ConnectAsync(new MqttClientCredentials(clientId1)).Wait();
            client.ConnectAsync(new MqttClientCredentials(clientId2)).Wait();

            subscriber1.SubscribeAsync("path", MqttQualityOfService.AtMostOnce)
                .ConfigureAwait(continueOnCapturedContext: false);

            subscriber1.MessageStream
                .Subscribe(m =>
                {
                    Console.WriteLine(Serializer.Deserialize<string>(m.Payload));
                });

            var message = new MqttApplicationMessage("path", Serializer.Serialize(Guid.NewGuid().ToString() + " :: " + DateTime.Now.ToString()));

            server.ClientConnected += (object sender, string e) =>
            {
                Console.WriteLine(sender.ToString());
            };
            for (int i = 0; i < 100; i++)
            {
                message = new MqttApplicationMessage("path", Serializer.Serialize(Guid.NewGuid().ToString() + " :: " + DateTime.Now.ToString()));                
                Thread.Sleep(200);
                client.PublishAsync(message, MqttQualityOfService.AtLeastOnce).Wait();
            }

            Console.WriteLine("Ready");

            var topic = Guid.NewGuid().ToString();

            Console.Read();

            server.Stop();
            client.DisconnectAsync().Wait();
            server.Dispose();
        }

        private static string GetClientId()
        {
            return string.Concat("Client", Guid.NewGuid().ToString().Replace("-", string.Empty).Substring(0, 15));
        }

        static ConcurrentBag<int> usedPorts;
        static Random random = new Random();

        private static int GetPort()
        {
            var port = random.Next(minValue: 40000, maxValue: 65535);

            if (usedPorts.Any(p => p == port))
            {
                port = GetPort();
            }
            else
            {
                usedPorts.Add(port);
            }

            return port;
        }

        private static IMqttClient GetClientAsync()
        {
            if (Configuration == null)
            {
                LoadConfiguration();
            }

            //Configuration.Port = GetPort();

            return MqttClient.CreateAsync(IPAddress.Loopback.ToString(), Configuration).Result;

            //var binding = new TcpBinding();
            //var initializer =  new MqttClientFactory(IPAddress.Loopback.ToString(), binding);

            //return initializer.CreateClientAsync(Configuration).Result;
        }

        private static IMqttServer GetServerAsync(IMqttAuthenticationProvider authenticationProvider = null)
        {
            try
            {
                LoadConfiguration();

                var binding = new ServerTcpBinding();
                var initializer = new MqttServerFactory(binding, authenticationProvider);
                var server = initializer.CreateServer(Configuration);

                server.Start();

                return server;
            }
            catch (MqttException protocolEx)
            {
                if (protocolEx.InnerException is SocketException)
                {
                    return GetServerAsync();
                }
                else
                {
                    throw;
                }
            }
        }

        private static ushort keepAliveSecs = 0;
        private static bool allowWildcardsInTopicFilters = true;
        private static object lockObject = new object();

        private static void LoadConfiguration()
        {
            lock (lockObject)
            {
                Configuration = new MqttConfiguration
                {
                    BufferSize = 128 * 1024,
                    //Port = 8883,
                    Port = 1883,
                    KeepAliveSecs = keepAliveSecs,
                    WaitTimeoutSecs = 5,
                    MaximumQualityOfService = MqttQualityOfService.ExactlyOnce,
                    AllowWildcardsInTopicFilters = allowWildcardsInTopicFilters
                };
            }
        }
    }
`

**Comment by mstranne** [comment]
Did you find a solution?

**Comment by nm-a** [comment]
I have been using other library

**Comment by mstranne** [comment]
Which one did you take?
And is it working for UWP also?

thanks,
Marco

**Comment by nm-a** [comment]
I am using this 
https://www.nuget.org/packages/M2Mqtt/

But this also very old one, I am planning to upgrade.

**Comment by daspuru** [comment]
MQTTnet is great!
