### ISSUE TITLE
Add link to Wiki from README.md

### ISSUE THREAD

**Issue by jhalbrecht** [xamarin/mqtt#126]
I added some samples to the Wiki. Perhaps a link to the project README.md could be added? 

Are maintainers aware of any other examples?

Some Examples

System.Net.Mqtt client sample A gist from @mauroa
xamarin-iot-samples/Hermes.Mqtt/ found in the xamarin/xamarin-iot-samples
Any others? Spicoli? Bueller?

**Comment by mauroa** [comment]
The readme has been updated with documentation and samples, so closing this ussue
