### ISSUE TITLE
Send an object

### ISSUE THREAD

**Issue by psummo** [xamarin/mqtt#128]
How I can send an object? I have my message  class with (string user, string message, datetime now).
I can't find a method that convert object into Byte Array to send/receive with this library

**Comment by mauroa** [comment]
Hi,
We don’t provide serialization capabilities for custom objects given that it’s up to the consumer to decide the type of serialization and content to send over the wire. The way that you get and build your byte[] is not part of the protocol specification. For example you can JSON serialize your class and encode to byte[], you can directly serialize to byte[], you can create your own package format and create the byte[], etc.
Given that we are an implementation of the MQTT protocol, we just take care of your business byte[] and apply the MQTT format on top of it and send it according to the spec in a transparent way.
That said, you can try with BinaryFormatter and a MemoryStream to directly convert your object in an easy way.

**Comment by psummo** [comment]
> That said, you can try with BinaryFormatter and a MemoryStream to directly convert your object in an easy way.

I try it but for UWP doesn't work.
So...ok sorry for bad issue.
