### ISSUE TITLE
Retrive CONNACK : how?

### ISSUE THREAD

**Issue by psummo** [xamarin/mqtt#129]
```
 var config = new MqttConfiguration{
                Port = 1883,
            };

            emitter = await MqttClient.CreateAsync("broker.net", config);
            emitter.ConnectAsync(new MqttClientCredentials("Mickey Mouse"), null, false);
```

How can retrive Connection ACK from ConnectAsync?

**Comment by mauroa** [comment]
Hi,
ConnectAck is an MQTT packet that only serves to consider the connection as completed, hence it doesn’t make sense to get an instance of CONNACK or have access to it at all.
To ensure that the connection ends accordingly you just need to await the ConnectAsync method. The internal implementation ensures that the connection returns when the ACK is received or when an error occurs, in which case it throws an exception. The same concept applies for Susbcribe, Publish, etc. All the ACK packets handling is encapsuled in the client methods so you just need to care about awaiting the corresponding API methods.

**Comment by psummo** [comment]
I know the function of ack, but ack mqtt contains if the session is clear or not. How I can know that? If it isnt clear I don't need to subscribe to the same topic.

Example
USER A --> Connect for first time to broker with clear session false
SERVER ACK--> will response with sessionPresentFlag (right?)
sessionPresentFlag at first connection with clean Session will be false because there's not old session. But if is not a first connection with old subscribe broker response is sessionPresentFlag = true

**Comment by mauroa** [comment]
Issue addressed recently, merged with this PR: https://github.com/xamarin/mqtt/pull/148.
Now, the way of getting the SessionPresent value is by using the return value of the IMqttClient.ConnectAsync, which is an enum that determines if the session has been cleared or preserved.
This will be available in the next release, coming soon.
Closing this issue
