### ISSUE TITLE
Message on Re connect: recive only offline message not all

### ISSUE THREAD

**Issue by psummo** [xamarin/mqtt#130]
I had try with MQTT.js to the same broke node.js and with publish/subscribe on QoS = 1, publish retain = false and connect cleanSession = false if

CLIENT A & CLIENT B ONLINE SUBSCRIBED TO THE SAME TOPIC
CLIENT A --> SEND MESSAGE 1/ MESSAGE 2/ MESSAGE 3--> CLIENT A/B REVICE MESSAGE 1/2/3
CLIENT B --> DISCONNECT
CLIENT A--> SEND MESSAGE 4/ MESSAGE 5--> CLIENT A REVICE MESSAGE 4/5
CLIENT B --> RE CONNECT --> CLIENT B RECIVE MESSAGE 4/5

With this xamarin client I recive ALL messages always on reconnect 
CLIENT A & CLIENT B ONLINE SUBSCRIBED TO THE SAME TOPIC
CLIENT A --> SEND MESSAGE 1/ MESSAGE 2/ MESSAGE 3--> CLIENT A/B REVICE MESSAGE 1/2/3
CLIENT B --> DISCONNECT
CLIENT A--> SEND MESSAGE 4/ MESSAGE 5--> CLIENT A REVICE MESSAGE 4/5
CLIENT B --> RE CONNECT --> CLIENT B RECIVE MESSAGE 1/2/3/4/5

**Comment by mauroa** [comment]
This bug has been addressed and fixed recently, merged in this PR: https://github.com/xamarin/mqtt/pull/147.
It will be available in the next release, coming soon.
Closing this issue.
