### ISSUE TITLE
Do it work on Xamarin Forms?

### ISSUE THREAD

**Issue by biapar** [xamarin/mqtt#131]
Do it work on Xamarin Forms?

**Comment by eduard1989** [comment]
Yes

**Comment by kbienert2** [comment]
Can someone explain to me how can I create a Xamarin project that works with this?

**Comment by mauroa** [comment]
System.Net.Mqtt is netstandard 2.0 compliant, so it works with any platform that supports it. To work with Xamarin.Forms just ensure you use netstandard in the library instead of PCL.
