### ISSUE TITLE
Last Will should have binary payload

### ISSUE THREAD

**Issue by kzu** [xamarin/mqtt#138]
According to [the spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc385349244) the last will message is no different than all other published messages: it contains a topic and a byte[] payload.

We unfortunately define it as a [string](https://github.com/xamarin/mqtt/blob/master/src/Client/MqttLastWill.cs#L23) which is later on converted to a `byte[]` when [publishing by the server](https://github.com/xamarin/mqtt/blob/master/src/Server/Sdk/Flows/ServerPublishReceiverFlow.cs#L48).

This should not be the case. To maintain some degree of backs compat, I'd flag this constructor and string property as obsolete with a warning (no error), hide it from intellisense with `EditorBrowsable` and provide a ctor overload receiving the `byte[]` payload instead. The legacy ctor would do the `UTF8.GetBytes` on the string so the backwards compat behavior is preserved.

**Comment by abrasat** [comment]
You are right.
Is there any concrete library release planned, which will support a binary payload for the LastWill message ?

**Comment by mauroa** [comment]
We are working on fixing many of the pending issues and also on some improvements, so we wait to release a new version soon.

**Comment by mauroa** [comment]
Fixed with PR: https://github.com/xamarin/mqtt/pull/146
It will be available soon in the next public release.
