### ISSUE TITLE
How can I create a Xamarin.Forms project that works with this?

### ISSUE THREAD

**Issue by kbienert2** [xamarin/mqtt#139]
How can I create a Xamarin project that works with this?
I tried so many times and forms on how to include into a blank Xamarin.Forms project and still fail.

**Comment by mauroa** [comment]
The latest version of the library is compatible with netstandard 2.0, so you should just create a Xamarin.Forms project with a netstandard library and install the Mqtt package in that library, which is referenced from the apps.
