### ISSUE TITLE
Evaluate incorporating common broker $SYS topics for admin

### ISSUE THREAD

**Issue by kzu** [xamarin/mqtt#15]
Reporting broker status via $SYS is pretty common in other brokers. We should evaluate and implement the most common and "standard" topics for reporting broker status.

See https://github.com/mqtt/mqtt.github.io/wiki/SYS-Topics

Take into account the suggestions on OASIS: https://issues.oasis-open.org/browse/MQTT-16 (in particular, the restriction that clients subscribing with wildcards should not receive $SYS messages.

This is apparently already part of the spec:

> 1. Applications MUST not define any topic names that start with a leading $ character 
> 2. MQTT server implementations MAY define topic names that start with the the string "$SYS/" 
> 3. MQTT server implementations MUST NOT define any other topics whose names start with a leading $ character. 

More context at https://groups.google.com/forum/#!topic/mqtt/ooRgMpe-Wa8, another broker implementing this at http://mosquitto.org/man/mosquitto-8.html

Story xamarin/XamarinVS#1888

**Comment by mariaghiondea** [comment]
Closing older issues - either done by now or low priority.
