### ISSUE TITLE
Application crashes unexpectedly when createasync is called

### ISSUE THREAD

**Issue by RayyanTahir** [xamarin/mqtt#152]
Hi, I tried both of the following ways , but both ways crash my application. I'm unable to debug with breakpoints because the debugger also crashes.

**Way 1**
```
client = await new System.Net.Mqtt.Sdk.MqttClientFactory(ServerAddress).CreateClientAsync(new MqttConfiguration()
{
     Port = ServerPort
});
```

**Way 2**
```
client = await MqttClient.CreateAsync(ServerAddress, ServerPort);
```

I'm debugging using my real phone connected to visual studio using `Xamarin Live Player`. Your help will be much appreciated.

**Comment by kzu** [comment]
`Xamarin Live Player` tries to interpret your code. We haven't done any testing of MQTT on it and likely won't. I'd suggest you run it on a real app instead.
