### ISSUE TITLE
Success/Failure status when publishing message with QoS=1 

### ISSUE THREAD

**Issue by ericsleung** [xamarin/mqtt#157]
Will there be a mechanism to report the success/failure status when publishing message with QoS=1? i.e. MqttQualityOfService.AtLeastOnce

**Comment by mauroa** [comment]
The same happens with the rest of protocol messages that involves an ACK. A completed Task without errors returned by the method indicates a successful completion, meaning the ACK received correctly and according to the protocol spec

**Comment by kzu** [comment]
Indeed @ericsleung, the intention is to use the API without having to know about the protocol internal details unless you need to. Just like a typical HTTP client throws an exception for non-OK responses, say (or used to anyway, the new one return a response and you inspect the result instead ;).
