### ISSUE TITLE
Looking for examples of how to set up the Server

### ISSUE THREAD

**Issue by lorenh** [xamarin/mqtt#159]
This project really intrigues me.  But I'd like to see an end-to-end example (via code or documentation) of how to set up a service to receive messages sent by a client that would be close to what I would need to implement if I were to use it.  The tests are only getting me so far in my understanding of it.  Any pointers to some other project that is using it?

**Comment by javirs85** [comment]
Same here. There is no documentation at all on the server side of it.. Or am I missing something ? I managed to start a 3rd party broker and push messages. Still did not manage to subscribe correctly and did not manage to create the server and connect to it from a python device (that IS actually capable of connecting to the 3rd party broker I'm using) 

Any resources?

**Comment by BullT** [comment]
Hi,

I have the same concern, I'm looking for a server sample to conecte a nodeMCU client.
