### ISSUE TITLE
What would be a good policy to maintain a healthy and stable connection between broker and client?

### ISSUE THREAD

**Issue by daspuru** [xamarin/mqtt#162]
Hi all! 

I am trying to make a rock solid connection between Android & iOS platforms. When the client and the broker are connected and I keep sending messages, everything runs with impressive performance.

My company have years of experience using Mqtt with hardware (Microchip, Raspberry, Arduino, C# & Xamarin now). As far as I have learned in field applications is that the low networking level needs to be constantly monitored, to trigger some retry policies, start or sending pings to have visibility of devices (all this in WiFi, and some in cabled Ethernet).

In my experience in field applications, any hardware or software that implements any TCP or UDP connection, when entering WiFi mode, mqtt is the only way to guarantee the delivery of the message in very high contaminated WiFI environment, however the maintenance of the connectivity is always an issue and needs to be very well reactive and observed.

Some things that I have observed with this library in my first experiments, is that the broker some times crashes with a System.Network level exception which I am not able to catch yet because I don't know in what part of the code is being thrown.

We are planning to write a policy and keep-alive connection layer, based in the Nuget Polly library, and your knowledge could provide a lot of help for us.

What are the main factors in your experience that makes the connections lost? By now I have discovered that sometimes, when I start the server, and it keeps time running, some times the client application can't connect to the broker one (iOS to Android and viceversa), so i need to start writing the layer described above.

Again, this is a great work, thanks a lot! :)

**Comment by arqueror** [comment]
Mqtt library is suddendly throwing an exception when sending messages to broker (sometimes takes 2 minutes, sometimes 5 minutes and sometimes is never thrown) . This is happenning to me with iOS broker and it makes application crash. Here is the complete exception stack:

Error: System.NullReferenceException; Object reference not set to an instance of an object
StackTrace:
"  at System.Net.Mqtt.Sdk.ServerPacketListener+<NotifyErrorAsync>d__25.MoveNext () [0x0003e] in <c6fa7d9657c247aabee5e1ee5da48e23>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 \n  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 \n  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 \n  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:447 \n  at System.Net.Mqtt.Sdk.ServerPacketListener+<>c__DisplayClass22_0+<<MonitorKeepAliveAsync>b__1>d.MoveNext () [0x00121] in <c6fa7d9657c247aabee5e1ee5da48e23>:0 \n--- End of stack trace from previous location where exception was thrown ---\n  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1034 \n  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x0000d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1308 \n  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957 \n  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904 \n  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00021] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1285 \n  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:858 \n  at ObjCRuntime.Runtime.ThreadPoolDispatcher (System.Func`1[TResult] callback) [0x00006] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:280 \n  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00009] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.14.0.14/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1210 "
