### ISSUE TITLE
Cannot create more than one client.

### ISSUE THREAD

**Issue by javirs85** [xamarin/mqtt#166]
I have a system where I have an object representing each of my devices. Wanted to add a "listener" on each device listening to some generic control channel and its particular channel. To simplify message handling.

But I get and exception when I try to create the second client. Is that the expected behavior ?

**Comment by NichtEuler** [comment]
Try using different clientIds to connect to your server.
When using the same string to identify your client the server won't accept the newer client using the same ID.
My workaround was this:
 `sessionState = await mqttClient.ConnectAsync(new MqttClientCredentials(Guid.NewGuid().ToString("N")),
                                cleanSession: true);`
