### ISSUE TITLE
Does xamarin / mqtt support TLS?

### ISSUE THREAD

**Issue by jhalbrecht** [xamarin/mqtt#170]
Does xamarin / mqtt support TLS?

If so is there a sample?

**Comment by inforaudio** [comment]
Do you find a solution but Xamarin and MQTT SSL?
Thanks

**Comment by jhalbrecht** [comment]
Check out [jhalbrecht/XamarinFormsMqttSample](https://github.com/jhalbrecht/XamarinFormsMqttSample) I just got a sample app working that demonstrates connecting to a mosquitto broker with a CA signed server certificate. I've connected to iot.eclipse.org on 8883 and my own mosquitto broker with a letsencrypt cert.

The repository also has several mosquitto_pub/sub examples as well as several python examples that programmatically accomplish the same goal.

The sample works off of various of the M2Mqtt forks for .net standard. I use the one by @mohaqeq [mohaqeq/paho.mqtt.m2mqtt](https://github.com/mohaqeq/paho.mqtt.m2mqtt) This NuGet works fine. [M2MqttDotnetCore 1.0.8](https://www.nuget.org/packages/M2MqttDotnetCore/)

I have a branch in the repository that uses this xamarin / mqtt client, but as far as I can tell this client doesn't support TLS.

**Comment by inforaudio** [comment]
Thanks for you suggestions.
We test you example and connect perfect to some public broker wiht SSL /TLS
I test in my 2 broker and we cant connect with you example.  I try to use ca.cert and ca.pfx and nothing dont connect.
So if use desktop app like MQTTBOX, we connect with certificate files, and if we connet with MQTT.FX we connect with ca.cert file.

Then i think that there are a problem in the broker configuracion.
How can check that the broker meets the requirements to work with your application??
Thanks for advance
