### ISSUE TITLE
Is Flespi supposed to work?

### ISSUE THREAD

**Issue by sebagomez** [xamarin/mqtt#177]
Sorry about the vague question but I'm new with MQTT I can't find a working example with C# and [Flespi](flespi.com).

I created the simplest sample from the README file and added my data:

```C#
try
{
	var configuration = new MqttConfiguration
	{
		Port = 31457
	};
	var client = MqttClient.CreateAsync("193.193.165.37", configuration).Result;
	var sessionState = client.ConnectAsync(new MqttClientCredentials(clientId: "test")).Result;
}
catch (Exception ex)
{
	while (ex != null)
	{
		Console.WriteLine(ex.Message);
		ex = ex.InnerException;
	}
}
```

and here's the error I get...
`Header Flag 7 is invalid for PublishReceived packet. Expected value: 0`

**Comment by xHasKx** [comment]
Hi Sebastian,

To connect to arbitrary MQTT broker in general you need such parameters:
* host and port
* username and password (both may be empty)

Parameters for flespi are described here: https://flespi.com/mqtt-broker#configuration

So I suppose you may try a code like this (didn't test it):
```csharp
var configuration = new MqttConfiguration
{
	KeepAliveSecs = 30, // to maintain connection alive when no events
	Port = 1883 // please note you should use 8883 port for secure SSL/TLS connection but I'm not sure it's supported in this library
};
var client = MqttClient.CreateAsync("mqtt.flespi.io", configuration).Result;
var sessionState = client.ConnectAsync(new MqttClientCredentials(clientId: "test", username: "<FLESPI-TOKEN>", password: "")).Result;
```
More info about `<FLESPI-TOKEN>` is here: https://flespi.com/kb/tokens-access-keys-to-flespi-platform

Also please note that async code using `await` is shown in the README of this lib, I think you should follow that pattern in your code too

**Comment by sebagomez** [comment]
It worked @xHasKx , thanks!
