### ISSUE TITLE
Error while connecting to localhost

### ISSUE THREAD

**Issue by nitishsantpur** [xamarin/mqtt#185]
Hi I am a novice and trying to connect to localhost using xamarin and using system.net.mqtt NuGet package but getting an exception system.net.mqtt.mqttclientexception I used the same example given in readme

**Comment by nitishsantpur** [comment]
```   public test()
        {
            InitializeComponent();

            publish();

        }




        private async void publish()
        {
            try {
                var configuration = new MqttConfiguration();
                var client = await MqttClient.CreateAsync("192.168.1.5", configuration);
                var sessionState = await client.ConnectAsync(new MqttClientCredentials(clientId: "foo"));
                await client.SubscribeAsync("foo/test2", MqttQualityOfService.AtMostOnce);

                client
                    .MessageStream
                    .Where(msg => msg.Topic == "foo/test2")
                    .Subscribe(msg => t.Text=msg.Topic);

            }

            catch (Exception e)
            {
                e.ToString();
            }
        }`//I am using mosquitto broker, id is foo and topic is test2

**Comment by kzu** [comment]
You should try reaching that host machine with a ping or some other protocol first. Most likely, you can't reach it at all. It will depend on various configurations of your Xamarin app (i.e. is it running in an emulator? a device? over wifi? USB? same network? firewall enabled? and on an on). 

So, my advice: just spin up a web site in your machine, try to hit it from a browser on that emulator/device. That's the first step to see if you have actual connectivity between the two, using the IP address as you're using in the above code.

**Comment by nitishsantpur** [comment]
Hi thanks for replying I tried using a website that I created using PHP and MySQL on my Samsung physical device using xampp it works fine after a bit of configuration changes
