### ISSUE TITLE
SubscribeAsync can't consume  MqttQualityOfService.AtLeastOnce QoS1 message

### ISSUE THREAD

**Issue by zitjubiz** [xamarin/mqtt#207]
`            var configuration = new MqttConfiguration();
            var client = MqttClient.CreateAsync("127.0.0.1", configuration).Result;
            var sessionState = client.ConnectAsync(new MqttClientCredentials(clientId: "foo1", userName: "admin", password: "1q2w3E*"), cleanSession: true).Result;

            await client.SubscribeAsync("foo/bar/topic1", MqttQualityOfService.AtLeastOnce); //QoS0 recv ok？？？ QoS1 fail with 10 nack
            Console.WriteLine("subscrib：" + "foo/bar/topic1");
            client
              .MessageStream
              .Subscribe(msg => {
                 
                  Console.WriteLine($"Message received in topic " + Encoding.UTF8.GetString(msg.Payload))
              });
`
SubscribeAsync can't consume  MqttQualityOfService.AtLeastOnce QoS1 message, fail with 10 nack
I am use rabbitmq with mqtt plugin to test.

**Comment by mariaghiondea** [comment]
Tracked internally with [Bug 1744988](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1744988): SubscribeAsync can't consume MqttQualityOfService.AtLeastOnce QoS1 message
